import React, { useState } from 'react';
import { 
  Settings, 
  Database, 
  Cpu, 
  Check, 
  Copy, 
  HelpCircle,
  AlertTriangle,
  RefreshCw,
  Eye,
  EyeOff
} from 'lucide-react';

interface ConfigData {
  NEXT_PUBLIC_SUPABASE_URL: string;
  NEXT_PUBLIC_SUPABASE_ANON_KEY: string;
  SUPABASE_SERVICE_ROLE_KEY: string;
  TELEGRAM_BOT_TOKEN: string;
  REQUIRE_MEDIA_CAPTION: string;
  TALLER_ORIGEN_ID?: string;
  TALLER_FORO_DESTINO_ID?: string;
}

interface ConnectionStatus {
  supabase: string; // 'CONNECTED' | 'CONNECTED_NO_TABLES' | 'DISCONNECTED' | 'ERROR'
  errorMessage: string;
  telegramActive: boolean;
}

interface ConfigSettingsProps {
  config: ConfigData;
  status: ConnectionStatus;
  onSaveConfig: (cfg: ConfigData) => Promise<void>;
  onRefreshStatus: () => void;
}

const SQL_INITIALIZATION = `-- =======================================================
-- SQL INITIALIZATION SCRIPT - MASTERTECH OS DASHBOARD
-- Ejecutar en el SQL Editor de tu Dashboard de Supabase
-- =======================================================

-- 1. Crear Tabla de Jornadas de Trabajo
CREATE TABLE IF NOT EXISTS jornadas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  telegram_id NUMERIC NOT NULL,
  username TEXT NOT NULL,
  started_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  ended_at TIMESTAMP WITH TIME ZONE,
  status TEXT DEFAULT 'ACTIVO'::text NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Crear Tabla de Plantillas de SOP
CREATE TABLE IF NOT EXISTS sops_templates (
  key TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  category TEXT DEFAULT 'recepcion'::text NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Crear Tabla de Respuestas / Expedientes SOP
CREATE TABLE IF NOT EXISTS sops_records (
  id TEXT PRIMARY KEY,
  category TEXT NOT NULL,
  template_key TEXT,
  title TEXT NOT NULL,
  client_name TEXT DEFAULT ''::text,
  vehicle TEXT DEFAULT ''::text,
  plate TEXT DEFAULT ''::text,
  creator TEXT DEFAULT 'Admin'::text NOT NULL,
  content TEXT NOT NULL,
  status TEXT DEFAULT 'Pendiente'::text NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Crear Tabla de Tópicos de Vehículos (Redirección de Media)
CREATE TABLE IF NOT EXISTS vehicle_topics (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  identifier text UNIQUE NOT NULL,
  thread_id integer NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- Indexar para optimización de búsquedas rápidas
CREATE INDEX IF NOT EXISTS idx_jornadas_telegram_id ON jornadas(telegram_id);
CREATE INDEX IF NOT EXISTS idx_sops_records_category ON sops_records(category);
CREATE INDEX IF NOT EXISTS idx_sops_records_plate ON sops_records(plate);
CREATE INDEX IF NOT EXISTS idx_vehicle_topics_identifier ON vehicle_topics(identifier);

-- Desactivar políticas RLS si es una API de administración o habilitar políticas permisivas para desarrollo rápido
ALTER TABLE jornadas DISABLE ROW LEVEL SECURITY;
ALTER TABLE sops_templates DISABLE ROW LEVEL SECURITY;
ALTER TABLE sops_records DISABLE ROW LEVEL SECURITY;
ALTER TABLE vehicle_topics DISABLE ROW LEVEL SECURITY;
`;

export default function ConfigSettings({ 
  config: initialConfig, 
  status, 
  onSaveConfig,
  onRefreshStatus
}: ConfigSettingsProps) {
  const [supabaseUrl, setSupabaseUrl] = useState(initialConfig.NEXT_PUBLIC_SUPABASE_URL);
  const [supabaseAnonKey, setSupabaseAnonKey] = useState(initialConfig.NEXT_PUBLIC_SUPABASE_ANON_KEY);
  const [supabaseRoleKey, setSupabaseRoleKey] = useState(initialConfig.SUPABASE_SERVICE_ROLE_KEY);
  const [botToken, setBotToken] = useState(initialConfig.TELEGRAM_BOT_TOKEN);
  const [requireMediaCaption, setRequireMediaCaption] = useState(initialConfig.REQUIRE_MEDIA_CAPTION === 'true');
  const [tallerOrigenId, setTallerOrigenId] = useState(initialConfig.TALLER_ORIGEN_ID || '');
  const [tallerForoDestinoId, setTallerForoDestinoId] = useState(initialConfig.TALLER_FORO_DESTINO_ID || '');
  
  const [copied, setCopied] = useState(false);
  const [saving, setSaving] = useState(false);
  const [showKeys, setShowKeys] = useState(false);
  const [saveSuccess, setSaveSuccess] = useState(false);

  const handleCopySql = () => {
    navigator.clipboard.writeText(SQL_INITIALIZATION);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault();
    setSaving(true);
    setSaveSuccess(false);

    try {
      await onSaveConfig({
        NEXT_PUBLIC_SUPABASE_URL: supabaseUrl.trim(),
        NEXT_PUBLIC_SUPABASE_ANON_KEY: supabaseAnonKey.trim(),
        SUPABASE_SERVICE_ROLE_KEY: supabaseRoleKey.trim(),
        TELEGRAM_BOT_TOKEN: botToken.trim(),
        REQUIRE_MEDIA_CAPTION: requireMediaCaption ? 'true' : 'false',
        TALLER_ORIGEN_ID: tallerOrigenId.trim(),
        TALLER_FORO_DESTINO_ID: tallerForoDestinoId.trim()
      });
      setSaveSuccess(true);
      setTimeout(() => {
        setSaveSuccess(false);
      }, 4000);
    } catch (err) {
      alert('Error guardando variables de entorno.');
    } finally {
      setSaving(false);
    }
  };

  const getStatusBadge = (supStatus: string) => {
    switch (supStatus) {
      case 'CONNECTED':
        return (
          <span className="flex items-center gap-1.5 text-xs text-emerald-400 bg-emerald-500/10 border border-emerald-500/20 px-3 py-1 rounded-full font-bold shadow-sm shadow-emerald-950/20">
            <span className="w-1.5 h-1.5 bg-emerald-400 rounded-full animate-pulse" />
            Conectado a Supabase
          </span>
        );
      case 'CONNECTED_NO_TABLES':
        return (
          <span className="flex items-center gap-1.5 text-xs text-amber-400 bg-amber-500/10 border border-amber-500/20 px-3 py-1 rounded-full font-bold shadow-sm shadow-amber-900/20">
            <AlertTriangle size={12} className="text-amber-400" />
            Conectado (Tablas Faltantes)
          </span>
        );
      case 'ERROR':
      case 'DISCONNECTED':
      default:
        return (
          <span className="flex items-center gap-1.5 text-xs text-rose-400 bg-rose-500/10 border border-rose-500/20 px-3 py-1 rounded-full font-bold shadow-sm shadow-rose-950/20">
            <span className="w-1.5 h-1.5 bg-rose-500 rounded-full" />
            Desconectado / Sandbox Local
          </span>
        );
    }
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
      
      {/* Left Column: API Configurations */}
      <div className="space-y-6">
        
        {/* Connection status card */}
        <div className="bg-zinc-900 border border-zinc-800/80 p-5 rounded-2xl shadow space-y-4">
          <div className="flex items-center justify-between border-b border-zinc-805 pb-3">
            <h3 className="font-bold text-white text-sm flex items-center gap-2">
              <Cpu size={16} className="text-sky-400" />
              Estado de Servicios
            </h3>
            <button 
              onClick={onRefreshStatus}
              className="p-1.5 bg-zinc-800 hover:bg-zinc-700 text-zinc-400 hover:text-zinc-200 rounded-lg transition"
              title="Probar de nuevo"
            >
              <RefreshCw size={14} />
            </button>
          </div>

          <div className="space-y-3">
            
            {/* Supabase status block */}
            <div className="flex items-center justify-between p-3 bg-zinc-950 rounded-xl border border-zinc-900">
              <div className="flex items-center gap-2 text-xs">
                <span className="text-xl">⚡</span>
                <div>
                  <span className="font-semibold text-zinc-300 block">Supabase Client DB</span>
                  <span className="text-zinc-550 text-[10px]">Almacenamiento remoto</span>
                </div>
              </div>
              {getStatusBadge(status.supabase)}
            </div>

            {/* Error Message if connection fails */}
            {status.errorMessage && (
              <div className="bg-rose-500/5 text-rose-400 border border-rose-500/10 text-xs p-3.5 rounded-xl space-y-1">
                <span className="font-bold block">Error devuelto por la base de datos:</span>
                <span className="font-mono break-all text-[11px] block">{status.errorMessage}</span>
                {status.supabase === 'CONNECTED_NO_TABLES' && (
                  <span className="block mt-1 font-sans text-amber-300 font-medium">💡 Ejecuta el script SQL de inicialización que se muestra a la derecha en la consola SQL de tu Supabase.</span>
                )}
              </div>
            )}

            {/* Telegram Bot status block */}
            <div className="flex items-center justify-between p-3 bg-zinc-950 rounded-xl border border-zinc-900">
              <div className="flex items-center gap-2 text-xs">
                <span className="text-xl">🤖</span>
                <div>
                  <span className="font-semibold text-zinc-300 block">Telegram Bot Listener</span>
                  <span className="text-zinc-550 text-[10px]">Webhook de Telegraf</span>
                </div>
              </div>
              {status.telegramActive ? (
                <span className="flex items-center gap-1.5 text-xs text-sky-400 bg-sky-505/10 border border-sky-500/20 px-3 py-1 rounded-full font-bold">
                  ● Token Configurado
                </span>
              ) : (
                <span className="flex items-center gap-1.5 text-xs text-zinc-500 bg-zinc-800/40 border border-zinc-700/30 px-3 py-1 rounded-full font-medium">
                  Falta token
                </span>
              )}
            </div>

            {/* Offline Sandbox notice */}
            {status.supabase !== 'CONNECTED' && (
              <div className="bg-sky-500/5 text-sky-400 border border-sky-500/10 text-xs p-3.5 rounded-xl">
                <span className="font-bold block mb-1">🎮 Modo Sandbox Local Activo</span>
                <span>
                  No hay credenciales válidas o las tablas no han sido creadas. 
                  El sistema está operando en <strong>Modo Local Offline</strong> guardando todos los cambios y plantillas en el archivo 
                  <code className="text-sky-300 px-1 bg-sky-950 rounded mx-1 text-[11px]">database_fallback.json</code> dentro del taller.
                  ¡Puedes usar, editar y crear absolutamente todo con persistencia garantizada en disco!
                </span>
              </div>
            )}

          </div>
        </div>

        {/* Credentials Form */}
        <div className="bg-zinc-900 border border-zinc-800/80 p-5 rounded-2xl shadow space-y-4">
          <div className="flex items-center justify-between border-b border-zinc-800 pb-3">
            <h3 className="font-bold text-white text-sm flex items-center gap-2">
              <Settings size={16} className="text-sky-400" />
              Configurar Claves (.env.local)
            </h3>
            <button 
              type="button"
              onClick={() => setShowKeys(!showKeys)}
              className="text-xs text-zinc-400 hover:text-zinc-200 transition flex items-center gap-1"
            >
              {showKeys ? <EyeOff size={13} /> : <Eye size={13} />}
              {showKeys ? 'Ocultar' : 'Revelar'}
            </button>
          </div>

          <form onSubmit={handleSave} className="space-y-4">
            
            {/* Supabase URL */}
            <div className="space-y-1">
              <label className="text-xs font-semibold text-zinc-400 block">Supabase URL (NEXT_PUBLIC_SUPABASE_URL)</label>
              <input 
                type={showKeys ? 'text' : 'password'} 
                value={supabaseUrl} 
                onChange={(e) => setSupabaseUrl(e.target.value)}
                placeholder="https://xxxx.supabase.co"
                className="w-full bg-[#18181b] border border-zinc-850 hover:border-zinc-800 focus:border-sky-500/30 focus:outline-none focus:ring-1 focus:ring-sky-500/20 text-white font-mono text-xs rounded-xl px-3 py-2.5 transition"
              />
            </div>

            {/* Supabase Anon Key */}
            <div className="space-y-1">
              <label className="text-xs font-semibold text-zinc-400 block">Supabase Anon Key (NEXT_PUBLIC_SUPABASE_ANON_KEY)</label>
              <input 
                type={showKeys ? 'text' : 'password'} 
                value={supabaseAnonKey} 
                onChange={(e) => setSupabaseAnonKey(e.target.value)}
                placeholder="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                className="w-full bg-[#18181b] border border-zinc-850 hover:border-zinc-800 focus:border-sky-500/30 focus:outline-none focus:ring-1 focus:ring-sky-500/20 text-white font-mono text-xs rounded-xl px-3 py-2.5 transition"
              />
            </div>

            {/* Supabase Service Role Key */}
            <div className="space-y-1">
              <div className="flex items-center justify-between">
                <label className="text-xs font-semibold text-zinc-400 block">Supabase Service Role Key (SUPABASE_SERVICE_ROLE_KEY)</label>
                <span className="text-[10px] text-zinc-550 border border-zinc-800 px-1.5 py-0.2 rounded bg-zinc-950 font-bold uppercase">Uso Interno</span>
              </div>
              <input 
                type={showKeys ? 'text' : 'password'} 
                value={supabaseRoleKey} 
                onChange={(e) => setSupabaseRoleKey(e.target.value)}
                placeholder="secret-service-role-key-for-bypass-rls..."
                className="w-full bg-[#18181b] border border-zinc-850 hover:border-zinc-800 focus:border-sky-500/30 focus:outline-none focus:ring-1 focus:ring-sky-500/20 text-white font-mono text-xs rounded-xl px-3 py-2.5 transition"
              />
            </div>

            {/* Telegram Bot Token */}
            <div className="space-y-1">
              <label className="text-xs font-semibold text-zinc-400 block">Telegram Bot Token (TELEGRAM_BOT_TOKEN)</label>
              <input 
                type={showKeys ? 'text' : 'password'} 
                value={botToken} 
                onChange={(e) => setBotToken(e.target.value)}
                placeholder="123456789:ABCdefGhIJKlmNoPQRsT..."
                className="w-full bg-[#18181b] border border-zinc-850 hover:border-zinc-800 focus:border-sky-500/30 focus:outline-none focus:ring-1 focus:ring-sky-500/20 text-white font-mono text-xs rounded-xl px-3 py-2.5 transition"
              />
            </div>

            {/* Redirección Nube Archivos */}
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-1">
                <label className="text-xs font-semibold text-zinc-400 block">Taller Origen ID</label>
                <input 
                  type="text"
                  value={tallerOrigenId} 
                  onChange={(e) => setTallerOrigenId(e.target.value)}
                  placeholder="-100xxxx"
                  className="w-full bg-[#18181b] border border-zinc-850 hover:border-zinc-800 focus:border-sky-500/30 focus:outline-none focus:ring-1 focus:ring-sky-500/20 text-white font-mono text-xs rounded-xl px-3 py-2.5 transition"
                />
              </div>
              <div className="space-y-1">
                <label className="text-xs font-semibold text-zinc-400 block">Taller Destino Foro ID</label>
                <input 
                  type="text"
                  value={tallerForoDestinoId} 
                  onChange={(e) => setTallerForoDestinoId(e.target.value)}
                  placeholder="-100yyyy"
                  className="w-full bg-[#18181b] border border-zinc-850 hover:border-zinc-800 focus:border-sky-500/30 focus:outline-none focus:ring-1 focus:ring-sky-500/20 text-white font-mono text-xs rounded-xl px-3 py-2.5 transition"
                />
              </div>
            </div>

            {/* Toggle for Strict Media Requirement */}
            <div className="flex items-center justify-between p-3 bg-zinc-950 rounded-xl border border-zinc-900 mt-2">
              <div>
                <span className="text-xs font-bold text-zinc-300 block">Exigir formato en fotos/videos</span>
                <span className="text-[10px] text-zinc-500 leading-tight block">Si está activo, el bot elimina las fotos que no incluyan modelo y número de orden en la descripción.</span>
              </div>
              <button
                type="button"
                onClick={() => setRequireMediaCaption(!requireMediaCaption)}
                className={`relative inline-flex h-5 w-9 shrink-0 cursor-pointer items-center justify-center rounded-full transition-colors duration-200 ease-in-out focus:outline-none ${
                  requireMediaCaption ? 'bg-sky-500' : 'bg-zinc-700'
                }`}
              >
                <span className="sr-only">Toggle</span>
                <span
                  aria-hidden="true"
                  className={`pointer-events-none inline-block h-3.5 w-3.5 transform rounded-full bg-white shadow ring-0 transition duration-200 ease-in-out ${
                    requireMediaCaption ? 'translate-x-2' : '-translate-x-2'
                  }`}
                />
              </button>
            </div>

            {/* Actions Bar */}
            <div className="flex items-center justify-between pt-2 border-t border-zinc-805">
              <div>
                {saveSuccess && (
                  <span className="text-xs font-bold text-emerald-400 animate-pulse border border-emerald-500/10 bg-emerald-500/5 px-2 py-0.5 rounded">
                    ✓ Configuración guardada.
                  </span>
                )}
              </div>
              <button 
                type="submit" 
                disabled={saving}
                className="flex items-center gap-1 bg-sky-500 hover:bg-sky-400 disabled:bg-zinc-800 text-white font-semibold text-xs px-4 py-2 rounded-xl transition"
              >
                {saving ? 'Guardando...' : 'Guardar y Recargar'}
              </button>
            </div>

          </form>
        </div>

      </div>

      {/* Right Column: SQL Initialization */}
      <div className="bg-zinc-900 border border-zinc-800/80 p-5 rounded-2xl shadow space-y-4 flex flex-col max-h-[85vh]">
        <div className="flex items-center justify-between border-b border-zinc-800 pb-3 shrink-0">
          <div>
            <h3 className="font-bold text-white text-sm flex items-center gap-2">
              <Database size={16} className="text-sky-400" />
              Tablas SQL Supabase Módulo
            </h3>
            <p className="text-zinc-500 text-xs">Crea la base de datos requerida para el panel en tu proyecto</p>
          </div>
          <button 
            onClick={handleCopySql}
            className="flex items-center gap-1.5 text-xs text-sky-400 hover:text-sky-300 font-semibold border border-sky-500/20 bg-sky-505/10 px-3 py-1.5 rounded-lg active:scale-95 transition"
          >
            {copied ? <Check size={13} /> : <Copy size={13} />}
            {copied ? 'Copiado!' : 'Copiar Script'}
          </button>
        </div>

        {/* SQL text viewer */}
        <div className="flex-1 overflow-auto bg-zinc-950 p-4 border border-zinc-900 rounded-xl">
          <pre className="text-[10px] text-zinc-400 leading-normal font-mono select-all break-inside-avoid">
            {SQL_INITIALIZATION}
          </pre>
        </div>

        {/* Help block */}
        <div className="bg-zinc-950 p-3 rounded-xl border border-zinc-900 text-zinc-500 text-xs shrink-0 select-none">
          <strong className="text-zinc-400 block mb-0.5">¿Cómo instalar?</strong>
          <ol className="list-decimal pl-4.5 space-y-0.5 text-zinc-550 leading-relaxed">
            <li>Copia este código haciendo clic en el botón superior.</li>
            <li>Inicia sesión en tu cuenta de <a href="https://supabase.com" target="_blank" className="text-emerald-450 hover:underline">Supabase Console</a>.</li>
            <li>Entra a la sección de <strong>SQL Editor</strong> de tu proyecto.</li>
            <li>Pega el código completo y presiona el botón de <strong>Run</strong>.</li>
            <li>El panel detectará automáticamente las tablas y se conectará en tiempo real.</li>
          </ol>
        </div>

      </div>

    </div>
  );
}
