export const FORUM_THREADS = {
  RECEPCION: 9,
  REPUESTOS: 11,
  OPERACIONES: 13,
  GARANTIAS: 15,
  PENDIENTES: 23,
  CALIDAD: 21,
  INSPECCION: 19,
  INCIDENCIAS: 17,
  MEJORA: 27,
  // Nuevos — Configurar con IDs reales usando /getid
  GERENCIA: parseInt(process.env.MANAGEMENT_THREAD_ID || '0'),
  // Grupos para redirección de media (Nube de Archivos)
  TALLER_ORIGEN_ID: parseInt(process.env.TALLER_ORIGEN_ID || '0'),
  TALLER_FORO_DESTINO_ID: parseInt(process.env.TALLER_FORO_DESTINO_ID || '0'),
} as const;

export const CALLBACKS = {
  NUEVO_INGRESO: 'NUEVO_INGRESO',
  SOLICITUD_REPUESTO: 'SOLICITUD_REPUESTO',
  COTIZACION_REPUESTO: 'COTIZACION_REPUESTO',
  NUEVOS_HALLAZGOS: 'NUEVOS_HALLAZGOS',
  LISTO_PARCIAL: 'LISTO_PARCIAL',
  ESTATUS_OP: 'ESTATUS_OP',
  FORMATO_QC: 'FORMATO_QC',
  GARANTIA_REINGRESO: 'GARANTIA_REINGRESO',
  GARANTIA_RETRABAJO: 'GARANTIA_RETRABAJO',
  PENDIENTES_POSTVENTA: 'PENDIENTES_POSTVENTA',
  PENDIENTES_SEGUIMIENTO: 'PENDIENTES_SEGUIMIENTO',
  INCIDENCIA_APERTURA: 'INCIDENCIA_APERTURA',
  INCIDENCIA_CIERRE: 'INCIDENCIA_CIERRE',
  LINEA_INSPECCION: 'LINEA_INSPECCION',
  MEJORA_APERTURA: 'MEJORA_APERTURA',
  MEJORA_CIERRE: 'MEJORA_CIERRE',
  JORNADA_INICIAR: 'JORNADA_INICIAR',
  JORNADA_FINALIZAR: 'JORNADA_FINALIZAR',
} as const;
