export const FORUM_THREADS = {
  RECEPCION: 9,
  REPUESTOS: 11,
  OPERACIONES: 13,
  GARANTIAS: 15,
  PENDIENTES: 23,
  CALIDAD: 13, // TODO: Update with real ID
  INSPECCION: 21, // TODO: Update with real ID
  INCIDENCIAS: 25, // TODO: Update with real ID
} as const;

export const CALLBACKS = {
  NUEVO_INGRESO: 'NUEVO_INGRESO',
  SOLICITUD_REPUESTO: 'SOLICITUD_REPUESTO',
  COTIZACION_REPUESTO: 'COTIZACION_REPUESTO',
  NUEVOS_HALLAZGOS: 'NUEVOS_HALLAZGOS',
  LISTO_PARCIAL: 'LISTO_PARCIAL',
  ESTATUS_OP: 'ESTATUS_OP',
  FORMATO_QC: 'FORMATO_QC',
} as const;
