export const FORUM_THREADS = {
  RECEPCION: 4,
  REPUESTOS: 11,
  CALIDAD: 13,
  OPERACIONES: 15,
  INSPECCION: 21,
  GARANTIAS: 23,
  INCIDENCIAS: 25,
} as const;

export const CALLBACKS = {
  NUEVO_INGRESO: 'NUEVO_INGRESO',
  SOLICITUD_REPUESTO: 'SOLICITUD_REPUESTO',
  COTIZACION_REPUESTO: 'COTIZACION_REPUESTO',
  NUEVOS_HALLAZGOS: 'NUEVOS_HALLAZGOS',
  LISTO_PARCIAL: 'LISTO_PARCIAL',
  ESTATUS_OP: 'ESTATUS_OP',
  FORMATO_QC: 'FORMATO_QC',
} as const;
